name: Cypress
on: pull_request
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install http-server
      - run: |
          openssl req -new -newkey rsa:4096 -days 365 -nodes -x509 \
          -subj "/C=SE/ST=STOCKHOLM/L=Stockholm/O=NET-UTIL/CN=localhost" \
          -keyout underlay/key.pem  -out underlay/cert.pem
      - name: Copy json data files to underlay
        run: 'cp cypress/fixtures/* underlay/json/'
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm run start
          wait-on: https://localhost:8443
        env:
          NODE_TLS_REJECT_UNAUTHORIZED: 0
