name: Cypress
on: pull_request
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: npm install http-server
      - run: |
          openssl req -new -newkey rsa:4096 -days 365 -nodes -x509 \
          -subj "/C=SE/ST=STOCKHOLM/L=Stockholm/O=NET-UTIL/CN=localhost" \
          -keyout underlay/key.pem  -out underlay/cert.pem
      - name: Copy json data files to underlay
        run: 'cp cypress/fixtures/* underlay/json/'
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: 'npm run start'
