name: Lint the ts code
on:
  push:
    paths:
      - 'js-src/**'
      - '.eslintrc.json'
      - '.github/workflows/'
jobs:
  lint:
    name: Linting
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@aabbfeb2ce60b5bd82389903509092c4648a9713
      - name: Install pre-requisites
        run: npm install
      - name: Lint
        run: npm run lint
